server:
  port: 8081

spring:
  application:
    name: library

  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: ITEM_USER
    password: PASSWORD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect